#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $DIR/base

mkdir -p $TARGET_DIR/provider
export PROVIDER_DIR=`realpath "$TARGET_DIR/provider"`

mkdir -p $TARGET_DIR/composition
export COMPOSITION_DIR=`realpath "$TARGET_DIR/composition"`

TUFAN_VERSION=`tufan --version`
echo using tufan-cli version $TUFAN_VERSION
